# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  branches:
    include: 
      - test-branch-01

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      name: azdevopsagent
    steps:
      
    - task: Docker@2
      inputs:
        containerRegistry: 'hungdangacr003'
        repository: 'dockerimage'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
    - task: Docker@2
      inputs:
        containerRegistry: 'hungdangacr003'
        repository: 'dockerimage'
        command: 'start'
    
